### PR TITLE
data format

### PR DESCRIPTION
**Pull request by lyzhangjm**
Hello, what is the data format .set ?  How can I download the available  data set ?

### CODE REVIEW

**Comment by Mensen** [comment]
Hi!. The ".set" format is the format used in EEGLAB. I used this because EEGLAB does a fantastic job of reading and converting almost any other type of data format so its pretty universal. Let me know if you have any difficulties loading your data with EEGLAB and I'll try to help out.

**Comment by Mensen** [comment]
About the pull request... I will merge develop into master soon enough once I finish testing a few of the new aspects. I would nonetheless encourage you to use the develop version since lots of things have changed in the meantime... and just let me know if there are any bugs.

**Comment by Mensen** [comment]
Also... I don't have a dataset available for download. But this is a good idea so I'll see if I can upload some data and work on the template as a good working example.

**Comment by lyzhangjm** [comment]
Thank you, I‘m looking forward to your upload some data. Because when I load the EEGlab data ,there is error either:

> > swa_SleepScoring
> > Warning: Out of range or non-integer values truncated during conversion to character. 
> > In fullfile at 50
> >   In swa_SleepScoring>menu_LoadEEG at 272 
> > Error using fullfile (line 93)
> > An unknown error occurred in FULLFILE while constructing the file specification.

Error in swa_SleepScoring>menu_LoadEEG (line 272)
tmp = memmapfile(fullfile(dataPath, EEG.data),...

Error while evaluating uimenu Callback

**Pull request closed without merging**
